### ISSUE TITLE
Add CI check for "go mod tidy"

### ISSUE THREAD

**Issue by invidian** [tinkerbell/cluster-api-provider-tink#10]
We shouldn't accept PRs which do not include changes from `go mod tidy` to keep repository clean.

**Comment by cpanato** [comment]
can i work on that?

**Comment by invidian** [comment]
>can i work on that?

Absolutely :+1: 

I was thinking about something similar to https://github.com/kinvolk/lokomotive/blob/7562ed7277757dbb3cff39467db6365b084d2126/Makefile#L183-L185, so this check can be run both locally and as part of the CI process with GitHub Actions.

**Comment by cpanato** [comment]
I will add other checks as well like the boilerplate and shell checks, similar we do for other providers, if you don't mind @invidian

**Comment by invidian** [comment]
Of course not. I guess we should also check for things like CRDs, manifests etc. I'm not super familiar with the project, so there might be more things we generate.
