### ISSUE TITLE
"make release-manifests" no longer works

### ISSUE THREAD

**Issue by invidian** [tinkerbell/cluster-api-provider-tink#28]
To run `clusterctl config cluster` locally, one must generate the `infrastructure-components.yaml` file which is done by `make release-manifests`, but this command currently prints the following error:
```
$ make release-manifests
release version v0.0.0
KUSTOMIZE_ENABLE_ALPHA_COMMANDS=true /tmp/test/cluster-api-provider-tink/hack/tools/bin/kustomize-v3.8.8 cfg set config image-tag v0.0.0
Error: unable to find "Krmfile" in package "config"
make: *** [Makefile:364: release-version] Error 1
```
CC @cpanato

**Comment by invidian** [comment]
Okay, I figured that I can run the following commands to workaround it:
```sh
KUSTOMIZE_ENABLE_ALPHA_COMMANDS=true /tmp/test/cluster-api-provider-tink/hack/tools/bin/kustomize-v3.8.8 cfg init config
KUSTOMIZE_ENABLE_ALPHA_COMMANDS=true /tmp/test/cluster-api-provider-tink/hack/tools/bin/kustomize-v3.8.8 cfg create-setter config/ image-tag v0.0.0 --type string
```

And then `make release-manifests` works. @cpanato I don't see any other CAPI provider to have `Krmfile`. Do you know what's going on here?

**Comment by cpanato** [comment]
sorry for the delay to reply.
i'm not 100% sure what is a `Krmfile`

**Comment by invidian** [comment]
I think 2b603dd39c2ed0b50f4c9e739c219a0531f5bbb3 broke it, as it was previously working for me.

Before we were using kustomize v3.8.7, now we use v3.8.8, I doubt they suddenly require `Krmfile` though :thinking:

**Comment by cpanato** [comment]
hum, i will take a look in the kustomize, will do that tomorrow morning (29.01.2021) is that ok?

**Comment by invidian** [comment]
Sure, there is no pressure on that I think, thanks! I'll actually bisect it in the meanwhile to pinpoint breaking commit.

**Comment by invidian** [comment]
Ah, it seems even on 8584f04380397b8cc97be7c7484314e701d6e456 it wasn't working. @gianarb any ideas?

**Comment by cpanato** [comment]
I just run locally using top of the main branch and downgrading kustomize and it works, although the command `USTOMIZE_ENABLE_ALPHA_COMMANDS=true $(KUSTOMIZE) cfg set config image-tag $(VERSION)` returned `set 0 fields`

**Comment by cpanato** [comment]
if that is expected we can revert the kustomize version to `v3.8.7`

**Comment by invidian** [comment]
Yeah, I figured the same. I think we should revert to `v3.8.7` then.

**Comment by cpanato** [comment]
agree for now, we can investigate in the future why this is a new thing
